[character]
success_symbol = "[ ğŸ](bold green)"
error_symbol = "[ ğŸ‘¹](bold red)"
[git_branch]
symbol = "ğŸŒ¿ "
style = "bold yellow"
[time]
format = "%H:%M:%S"
style = "bold blue"
[username]
style_user = "bold green"
style_root = "bold red"
format = "[$user]($style)"
disabled = false
[hostname]
ssh_only = true
format = "[@$hostname](bold green)"
[directory]
style = "bold green"
format = "[$path]($style) "
truncation_length = 3
truncation_symbol = "â€¦/"
[git_status]
conflicted = "ğŸ’£"
ahead = "ğŸ“¤"
behind = "ğŸ“¥"
diverged = "ğŸ˜µ"
untracked = "ğŸ¤·"
stashed = "ğŸ“¦"
modified = "âœï¸ "
staged = "ğŸ“¦"
renamed = "ğŸ”„"
deleted = "ğŸ—‘ï¸ "
style = "bold red"
[docker_context]
symbol = " ğŸ³ "
style = "bold blue"
format = "[$symbol$context]($style)"

